image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:cw-bump-leeway.29
workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
tasks:
  - name: Workspace Prep
    init: |
      ./scripts/authenicate-uplink-cli.sh || true
    before: |
      ./scripts/docker-cli-login.sh || true
      direnv allow
  - name: Golang Deps
    init: direnv reload; leeway exec --filter-type go -v -- go mod verify
    openMode: split-right
vscode:
  extensions:
    - EditorConfig.EditorConfig
    - golang.go
    - ms-azuretools.vscode-docker
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - eamodio.gitlens
    - exiasr.hadolint
    - gitlab.gitlab-workflow
