packages:
  - name: app
    type: generic
    config:
      commands: [["echo"]]
    deps:
      - :app-linux-amd64
      - :app-linux-arm64
      - :app-linux-386
  - name: app-linux-amd64
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
    deps:
      - :version
      - components/supervisor-api/go:lib
      - components/gitpod-protocol/go:lib
      - components/local-app-api/go:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    prep:
      - ["cp", "_deps/components-local-app--version/version.txt", "version.txt"]
    config:
      packaging: app
  - name: app-linux-arm64
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
    deps:
      - :version
      - components/supervisor-api/go:lib
      - components/gitpod-protocol/go:lib
      - components/local-app-api/go:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=arm64
    prep:
      - ["cp", "_deps/components-local-app--version/version.txt", "version.txt"]
    config:
      packaging: app
  - name: app-linux-386
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
    deps:
      - :version
      - components/supervisor-api/go:lib
      - components/gitpod-protocol/go:lib
      - components/local-app-api/go:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=386
    prep:
      - ["cp", "_deps/components-local-app--version/version.txt", "version.txt"]
    config:
      packaging: app
  - name: version
    type: generic
    argdeps:
      - localAppVersion
    config:
      commands:
        - ["sh", "-c", "echo '${localAppVersion}' > version.txt"]
        - ["echo", "Local App Version: ${localAppVersion}"]
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      buildArgs:
        VERSION: ${version}
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/gp-localapp:${version}
        - ${imageRepoBase}/gp-localapp:commit-${__git_commit}
