packages:
  - name: docker
    type: docker
    argdeps:
      - imageRepoBase
    config:
      dockerfile: ajhalili2006-experiments.Dockerfile
      image:
        - ${imageRepoBase}/gp-localapp-glci-builder-devenv:${version}
